{"name": "insights.specs.Specs.etc_udev_40_redhat_rules", "exec_time": 2.3603439331054688e-05, "errors": ["Traceback (most recent call last):\n  File \"/var/lib/insights/last_stable.egg/insights/core/serde.py\", line 195, in dehydrate\n    doc[\"results\"] = marshal(value, root=self.data, pool=self.pool)\n  File \"/var/lib/insights/last_stable.egg/insights/core/serde.py\", line 106, in marshal\n    return f(v)\n  File \"/var/lib/insights/last_stable.egg/insights/core/serde.py\", line 85, in serialize\n    \"object\": to_dict(obj, root=root),\n  File \"/var/lib/insights/last_stable.egg/insights/core/spec_factory.py\", line 1041, in serialize_text_file_provider\n    rc = obj.write(dst)\n  File \"/var/lib/insights/last_stable.egg/insights/core/spec_factory.py\", line 288, in write\n    p.write(dst)\n  File \"/var/lib/insights/last_stable.egg/insights/util/subproc.py\", line 155, in write\n    six.reraise(be.__class__, be, sys.exc_info()[2])\n  File \"/usr/lib/python3.6/site-packages/six.py\", line 693, in reraise\n    raise value\n  File \"/var/lib/insights/last_stable.egg/insights/util/subproc.py\", line 151, in write\n    raise CalledProcessError(rc, self.cmds[0], \"\")\ninsights.util.subproc.CalledProcessError: (1, ['grep', '-F', 'SUBSYSTEM!=\"memory\", ACTION!=\"add\", GOTO=\"memory_hotplug_end\"', '/usr/lib/udev/rules.d/40-redhat.rules'], '')\n"], "results": null, "ser_time": 0.003693819046020508}